### ISSUE TITLE
opswatgears.com - Security Monitoring

### ISSUE THREAD

**Issue by TraderStf** [drduh/OS-X-Yosemite-Security-and-Privacy-Guide#20]
Not an anti-virus/malware, more a security monitoring and reporting tool for desktop computers, laptop, virtual machines and servers!

Really great, just installed it on our 5 devices.

What advantage I see with gears: if one of 'your' devices is 'compromised' you can warn its owner to avoid to connect to others and take action to restore it.

Free for 25 devices.
https://www.opswatgears.com/

**Comment by sg-s** [comment]
closed-source application that you have to install on your computer? 

installing something that you can't look at the source for is insecure by design, and the security of your computer boils down to how much you're willing to trust these people. 

besides, what sort of scenario involves you giving your device to someone, but you having the power to install something on that computer, and they not minding?  

i'm sorry but i don't understand how this improves security.

**Comment by drduh** [comment]
Agree with @sg-s and also this software seems a bit too esoteric for a general security guide.

Open source software should be preferred. I added mention of this to the guide. @TraderStf maybe you can accomplish the features you like of the software with open source alternatives?

**Comment by TraderStf** [comment]
@sg-s
- a lot of items in OSX are without public source codes...
- I was thinking to a support team which manages several devices for the employees, being able to 'remotely' control their devices is far more simpler, reduce the risks of 'affecting/infecting' other systems, employees and external people because their devices is not up-to-date.

I leave this Open as I don't know if @drduh wants to cover such cases, multiple users and/or affecting others.

**Comment by sg-s** [comment]
> I was thinking to a support team which manages several devices for the employees, being able to 'remotely' control their devices is far more simpler, reduce the risks of 'affecting/infecting' other systems, employees and external people because their devices is not up-to-date.

Hi @TraderStf not sure if this is the typical use case here...
